### PR TITLE
Rename polymorphic_value<T> to polymorphic<T>

### PR DESCRIPTION
**Pull request by jbcoe**

### CODE REVIEW

**Comment by jbcoe** [comment]
Failing tests baffle me https://github.com/jbcoe/polymorphic_value/pull/132

Seems bazel thinks we're only requesting C++0x. Not sure why .bazelrc is not read.

**Comment by jbcoe** [comment]
Bazel seems to be ignoring my efforts to set a C++ standard version:

```
ERROR: /home/runner/work/polymorphic_value/polymorphic_value/BUILD.bazel:7:8: Compiling polymorphic_test.cpp failed: (Exit 1): gcc failed: error executing command (from target //:polymorphic_test) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 32 arguments skipped)
```

**Comment by jbcoe** [comment]
Request for c++17/c++20 does get through to the compiler. `constexpr` issue looks real - will investigate.

**Comment by jbcoe** [comment]
Issues fixed by updating Catch version to 2.13.10

**Comment by jbcoe** [comment]
@Twon I’d like to go ahead with the rename unless you object.

**Review by Twon — APPROVED** [review]
@jbcoe changes look good.  We need to update the paper too.  Perhaps open a ticket to track this?

Also, I'll need to update the Conan package sometime, we should also track that.

**Comment by jbcoe** [comment]
I think we should bump major version number as part of this commit - WDYT?

**Pull request closed without merging**
