### PR TITLE
Modern cmake

### PR DESCRIPTION
**Pull request by Twon**

### CODE REVIEW

**Comment by Twon** [comment]
Looks like the fact I've enabled sanitizers by default breaks the GCC build.  The python setup script should probably be extended to expose this.  Also it doesn't seem to find address sanitizer correctly which is weird, I need to look into this further.

**Comment by jbcoe** [comment]
2 stalled CI builds looks odd.
The mix of appveyor and travis is odder still.

Code looks great - happy to merge when tests pass.

**Comment by Twon** [comment]
Cool, I'm going to add one or two more changes before I merge.  I'm planning to extend how this can be included in a project by making the CMake target directly includable via the projects CMakelist.txt file in the same way that we include the Catch test framework now (requires an alias and adding the include directory to the polymorphic_value target).  

I'm also going to extend the project to have an install method when not being included directly (again like Catch does).   I'll later add a Conan configuration file which will piggyback off this to create the package.  Also, I want to add a natvis file for making this easier to debug in Visual Studio and add code coverage for the unit tests.

**Comment by jbcoe** [comment]
Might be worth doing in follow-up PRs?

**Comment by Twon** [comment]
> Might be worth doing in follow-up PRs?
> […](#)
> On 9 Dec 2018, at 15:03, Antony Peacock ***@***.***> wrote: Cool, I'm going to add one or two more changes before I merge. I'm planning to extend how this can be included in a project by making the CMake target directly includable via the projects CMakelist.txt file in the same way that we include the Catch test framework now (requires an alias and adding the include directory to the polymorphic_value target). I'm also going to extend the project to have an install method when not being included directly (again like Catch does). I'll later add a Conan configuration file which will piggyback off this to create the package. Also, I want to add a natvis file for making this easier to debug in Visual Studio and add code coverage for the unit tests. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Sure thing, I'll split this up into separate before submitting

**Comment by Twon** [comment]
Closing as this has been split up into multiple pull requests

**Pull request closed without merging**
